### ISSUE TITLE
Firestore rules definieren

### ISSUE THREAD

**Issue by guischi** [guischi/WSK-Reservationssystem#24]
Aktuell gibt es in der Firebase DB noch unsichere resp. keine Security Rules. Dies muss nachgezogen werden.

**Comment by kguggenbuehl** [comment]
Ich habe mal Rules definiert, welche für mich Sinne ergaben. Nun gibt es ein Fehler beim Logout, wenn ich in den Usereinstellungen bin, dass die Permissions fehlen. Ich nehme an, da wird noch etwas von der DB gebraucht, nachdem man ausgeloggt ist. (Dann hat man keine Rechte mehr, um gewisse DBs zu lesen). Muss vor dem Logout noch etwas unsubscribed werden?
