### ISSUE TITLE
Id-Feld auf Booking-Einträgen

### ISSUE THREAD

**Issue by guischi** [guischi/WSK-Reservationssystem#51]
Bei Booking-Einträgen in der DB gibt es aktuell kein ID-Feld. Der Key setzt sich wohl zusammen aus dateString und userId. Allenfalls könnte man ein Id-Feld setzen (entsprechend der Document Id).

**Comment by kguggenbuehl** [comment]
Werde die id noch reinnehmen entsprechend der Document-Id.
