### ISSUE TITLE
Passwort ändern-Button in den User-Einstellungen führt zum 404

### ISSUE THREAD

**Issue by kguggenbuehl** [guischi/WSK-Reservationssystem#78]

**Comment by guischi** [comment]
Konnte das nicht reproduzieren. Hast du den neuesten Stand vom develop?

**Comment by kguggenbuehl** [comment]
Ja, habe ich. Egal welcher User, wenn ich oben rechts die Einstellungen anwähle und da "Mein Passwort ändern" klicke, kommt die 404, da er die Route anscheinend nicht auflösen kann.
