### ISSUE TITLE
Fehler beim Ausloggen: "TypeError: Cannot read property 'uid' of null"

### ISSUE THREAD

**Issue by kguggenbuehl** [guischi/WSK-Reservationssystem#81]

**Comment by guischi** [comment]
Auch das konnte ich nicht nachvollziehen. Trat das im Chrome auf?

**Comment by guischi** [comment]
Hatte den Fehler im IE/Edge auch... Das Problem liegt in der Booking-Component, auf Zeile 94. Wenn der User ausgeloggt ist schiesst diese Subscription vermutlich nochmal. Da müsste man noch einen Check einbauen ob user nicht null bzw undefined ist.
